### ISSUE TITLE
토큰을 쿠키 또는 헤더에서 어떻게 읽어와야 하는지

### ISSUE THREAD

**Issue by ahn-sj** [OnNaNOn/OMG#41]
ajax로 서버로부터 200번 응답을 받을 경우 success가 실행될 때 다음 문장을 실행시키도록 했다.
`window.location.href = '/admin/management';`

다만 위의 문제점은 alert가 뜨는 잠시 동안에 쿠키에 토큰이 담기지만 그 이후에는 증발되는 문제가 있었다.
이걸 프론트에서 계속 들고다니는 코드를 추가해주어야 하는지??

만약 토큰을 가지고 있지 않은 경우라면 다음과 같은 InvalidDefinitionException이 발생한다.

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.springframework.http.ResponseEntity$DefaultBuilder and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1300)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:46)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:29)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4568)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3821)
	at com.ono.omg.security.jwt.AuthenticationEntryPointException.commence(AuthenticationEntryPointException.java:22)

**Comment by ahn-sj** [comment]
프론트 매니저님이 멘토링 해주신 결과 현재 ajax 코드와 서버 사이드 렌더링 방식의 통합이 불가능하다는 답변을 받음
대안 1. ajax로 Response를 서버로부터 받아서 화면에 출력
대안 2. react 사용

**Comment by iswoos** [comment]
ajax로 진행하는 대안 1이 가장 합리적인 선택같습니다!

현재 프로젝트 중간마감 기한까지 약 1일 남은 것을 고려하면, 교육 및 적용에 시간리소스가 많이 투입될 것으로 예상되는 대안 2보다는 대안 1이 나을 것으로 판단됩니다.

**Comment by ahn-sj** [comment]
팀원들과 회의한 결과 ajax로 진행하는 걸로 결정되었습니다.
